"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useRef, useState } from "react";
import { MeetingPreview } from "./MeetingPreview";
import { saveLivrable } from "@/app/(app)/livrables/actions";
import { completeWorkflowStep } from "@/app/(app)/workflows/actions";
import { useRouter } from "next/navigation";
import type { BrandKit } from "@prisma/client";

type MeetingType = "Premier RDV" | "Démo produit" | "Négociation" | "Suivi client" | "Réunion de closing";
type Objective = "Qualifier le prospect" | "Présenter la solution" | "Obtenir un engagement" | "Fidéliser" | "Réactiver";

const meetingTypes: { id: MeetingType; emoji: string; desc: string }[] = [
  { id: "Premier RDV", emoji: "🤝", desc: "Découverte et qualification" },
  { id: "Démo produit", emoji: "🖥️", desc: "Présentation de la solution" },
  { id: "Négociation", emoji: "⚖️", desc: "Discussion tarifaire et conditions" },
  { id: "Suivi client", emoji: "📞", desc: "Point d'avancement client existant" },
  { id: "Réunion de closing", emoji: "🎯", desc: "Signature et engagement final" },
];

const objectives: Objective[] = [
  "Qualifier le prospect",
  "Présenter la solution",
  "Obtenir un engagement",
  "Fidéliser",
  "Réactiver",
];

type Brief = any;

type MeetingStudioProps = {
  workflowId?: string
  stepId?: string
  previousOutput?: Record<string, unknown> | null
  brandKit?: BrandKit| null
}

export function MeetingStudio({ workflowId, stepId, previousOutput,brandKit }: MeetingStudioProps){
  const [meetingType, setMeetingType] = useState<MeetingType>("Premier RDV");
  const [prospectSector, setProspectSector] = useState((previousOutput?.sector as string) ?? brandKit?.sector ?? "");
  const [prospectRole, setProspectRole] = useState((previousOutput?.prospectRole as string) ?? "");
  const [prospectContext, setProspectContext] = useState("");
  const [objective, setObjective] = useState<Objective>("Qualifier le prospect");
  const [loading, setLoading] = useState(false);
  const [brief, setBrief] = useState<Brief | null>(null);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [completingStep, setCompletingStep] = useState(false);
  const router = useRouter();

 

async function autoGenerate(sector: string, prospectRole: string) {
  setLoading(true);
  setBrief(null);
  setError(null);
  try {
    const res = await fetch("/api/agents/mehdi/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ meetingType, prospectSector: sector, prospectRole, prospectContext, objective }),
    });
    const data = await res.json();
    if (data.success) setBrief(data.brief);
    else setError("Erreur lors de la génération. Réessayez.");
  } catch {
    setError("Erreur réseau.");
  } finally {
    setLoading(false);
  }
}

const hasAutoGenerated = useRef(false);

useEffect(() => {
  if (previousOutput?.sector && previousOutput?.prospectRole && !hasAutoGenerated.current) {
    hasAutoGenerated.current = true;
    const sector = previousOutput.sector as string;
    const role = previousOutput.prospectRole as string;
    setTimeout(() => autoGenerate(sector, role), 0);
  }
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, []);

  async function handleCompleteStep() {
    if (!workflowId || !stepId || !brief) return;
    setCompletingStep(true);
    await completeWorkflowStep(workflowId, stepId, {
      meetingType,
      prospectSector,
      prospectRole,
      brief,
    });
    router.push(`/workflows/${workflowId}`);
  }

  async function handleGenerate() {
    if (!prospectSector.trim() || !prospectRole.trim()) return;
    setLoading(true);
    setBrief(null);
    setError(null);
    setSaved(false);

    try {
      const res = await fetch("/api/agents/mehdi/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ meetingType, prospectSector, prospectRole, prospectContext, objective }),
      });
      const data = await res.json();
      if (data.success) {
        setBrief(data.brief);
      } else {
        setError("Erreur lors de la génération. Réessayez.");
      }
    } catch {
      setError("Erreur réseau.");
    } finally {
      setLoading(false);
    }
  }

  async function handleSave() {
    if (!brief) return;
    const content = `## ${meetingType} — ${prospectRole} (${prospectSector})

**Résumé :** ${brief.summary}

## Agenda
${brief.agenda.map((s: string, i: number) => `${i + 1}. ${s}`).join("\n")}

## BANT
- **Budget :** ${brief.bant.budget}
- **Décideur :** ${brief.bant.authority}
- **Besoin :** ${brief.bant.need}
- **Calendrier :** ${brief.bant.timeline}

## Questions clés
${brief.questions.map((q: any) => `- [${q.category}] ${q.question}`).join("\n")}

## Objections & réponses
${brief.objections.map((o: any) => `- ⚠ ${o.objection}\n  → ${o.reponse}`).join("\n")}

💡 **Conseil :** ${brief.tip}`;

    await saveLivrable({
      agentSlug: "mehdi",
      title: `Fiche réunion — ${meetingType} · ${prospectRole}`,
      content,
    });
    setSaved(true);
  }

  return (
    <div className="min-h-screen bg-[#0F1117] text-white">
      <div className="border-b border-[#2A2D3E] bg-[#1C1F2E]/60 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-3">
          <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-blue-700 flex items-center justify-center text-sm font-bold">M</div>
          <div>
            <h1 className="font-semibold text-sm text-white" style={{ fontFamily: "'Bricolage Grotesque', Inter, sans-serif" }}>Studio Mehdi</h1>
            <p className="text-xs text-gray-500">MeetingStudio — Préparation de réunions B2B & qualification BANT</p>
          </div>
          <div className="ml-auto flex items-center gap-2">
            {brief && !saved && (
              <button onClick={handleSave} className="text-xs bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg font-medium transition-colors">
                Enregistrer la fiche
              </button>
            )}
            {saved && <span className="text-xs text-emerald-400 font-medium">✓ Enregistré</span>}
            {workflowId && stepId && brief && (
              <button onClick={handleCompleteStep} disabled={completingStep}
                className="text-xs bg-[#7C5CFC] hover:bg-[#6B4FDB] disabled:opacity-50 text-white px-4 py-2 rounded-lg font-medium transition-colors">
                {completingStep ? "En cours…" : "Terminer cette étape →"}
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-5 gap-8">
        <div className="lg:col-span-2 space-y-5">
          <section className="space-y-3">
            <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Type de réunion</h2>
            <div className="space-y-2">
              {meetingTypes.map((m) => (
                <button key={m.id} onClick={() => setMeetingType(m.id)}
                  className={`w-full flex items-center gap-3 p-3 rounded-xl border text-left transition-all ${meetingType === m.id ? "border-indigo-500 bg-indigo-500/10" : "border-[#2A2D3E] bg-[#1C1F2E] hover:border-[#3A3D4E]"}`}>
                  <span className="text-lg">{m.emoji}</span>
                  <div>
                    <p className="text-sm font-medium text-white">{m.id}</p>
                    <p className="text-xs text-gray-500">{m.desc}</p>
                  </div>
                  {meetingType === m.id && <span className="ml-auto w-2 h-2 rounded-full bg-indigo-400" />}
                </button>
              ))}
            </div>
          </section>
          <section className="space-y-2">
            <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Prospect</h2>
            <input value={prospectSector} onChange={(e) => setProspectSector(e.target.value)}
              placeholder="Secteur (ex : Immobilier, Agroalimentaire…)"
              className="w-full bg-[#1C1F2E] border border-[#2A2D3E] rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-indigo-500 transition-colors" />
            <input value={prospectRole} onChange={(e) => setProspectRole(e.target.value)}
              placeholder="Poste (ex : Directeur Général, DAF…)"
              className="w-full bg-[#1C1F2E] border border-[#2A2D3E] rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-indigo-500 transition-colors" />
          </section>
          <section className="space-y-2">
            <label className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Contexte connu <span className="text-gray-600 font-normal normal-case">(optionnel)</span></label>
            <textarea value={prospectContext} onChange={(e) => setProspectContext(e.target.value)} rows={3}
              placeholder="Ce que vous savez déjà du prospect, ses enjeux, une conversation précédente…"
              className="w-full bg-[#1C1F2E] border border-[#2A2D3E] rounded-xl px-4 py-3 text-sm text-white placeholder-gray-600 resize-none focus:outline-none focus:border-indigo-500 transition-colors" />
          </section>
          <section className="space-y-2">
            <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Objectif</h2>
            <div className="space-y-1">
              {objectives.map((o) => (
                <button key={o} onClick={() => setObjective(o)}
                  className={`w-full text-left text-xs px-3 py-2 rounded-lg border font-medium transition-all ${objective === o ? "border-indigo-500 bg-indigo-500/20 text-indigo-300" : "border-[#2A2D3E] text-gray-400 hover:border-gray-500"}`}>
                  {o}
                </button>
              ))}
            </div>
          </section>
          <button onClick={handleGenerate} disabled={loading || !prospectSector.trim() || !prospectRole.trim()}
            className="w-full py-3 rounded-xl font-semibold text-sm transition-all disabled:opacity-40 disabled:cursor-not-allowed bg-indigo-600 hover:bg-indigo-500 text-white">
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Mehdi prépare votre réunion…
              </span>
            ) : "Préparer la réunion"}
          </button>
          {error && <p className="text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-2">{error}</p>}
        </div>
        <div className="lg:col-span-3">
          {brief ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <MeetingPreview brief={brief} meetingType={meetingType} prospectRole={prospectRole} prospectSector={prospectSector} />
            </div>
          ) : (
            <div className="h-full min-h-64 flex flex-col items-center justify-center text-center rounded-2xl border border-dashed border-[#2A2D3E] p-12">
              <div className="w-14 h-14 rounded-2xl bg-[#1C1F2E] flex items-center justify-center text-2xl mb-4">📋</div>
              <p className="text-gray-400 text-sm font-medium">Votre fiche de réunion apparaîtra ici</p>
              <p className="text-gray-600 text-xs mt-1">Choisissez le type de réunion, décrivez le prospect, et préparez</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}